# Generated by Django 3.2.5 on 2022-12-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20221229_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='tag',
            new_name='tags',
        ),
    ]
