# Generated by Django 3.2.5 on 2022-12-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_tag_projects_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='featured_image',
            field=models.ImageField(blank=True, default='default_logo.png', null=True, upload_to=''),
        ),
    ]
