# Generated by Django 5.0.1 on 2024-01-21 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_timetracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
    ]
